### ISSUE TITLE
controller-manager never deploys due to operator forcing a DS update

### ISSUE THREAD

**Issue by sjenning** [openshift/cluster-openshift-controller-manager-operator#17]
xref https://github.com/openshift/installer/issues/438

@rphillips @deads2k 

What I'm seeing is that the `controller-manager` Daemonset in the `openshift-controller-manager` Project is having its `operator.openshift.io/force` annotation periodically changed causing the pod to never stay up long.  `controller-manager` Pod are always being created, then terminated.  The `generation` on the Daemonset increases rapidly.

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    operator.openshift.io/force: 2c6fa783-cc12-11e8-b0e5-0a580a020105
  creationTimestamp: 2018-10-09T19:42:26Z
  generation: 492
```

Doing a `watch -n3 -d oc get ds controller-manager -o yaml`, one can see the `operator.openshift.io/force` change, resulting in a bump of the `generation` and the termination of any pods.
